/* tslint:disable */
/* eslint-disable */
export const __wbg_ocrengine_free: (a: number, b: number) => void;
export const __wbg_ocrenginebuilder_free: (a: number, b: number) => void;
export const ocrengine_inferenceThreads: (a: number) => number;
export const ocrengine_run: (a: number, b: number, c: number) => [number, number, number];
export const ocrengine_runWithMetrics: (a: number, b: number, c: number) => [number, number, number];
export const ocrenginebuilder_build: (a: number) => [number, number, number];
export const ocrenginebuilder_cropMode: (a: number, b: number, c: number) => [number, number, number];
export const ocrenginebuilder_detLimitSideLen: (a: number, b: number) => number;
export const ocrenginebuilder_detLimitType: (a: number, b: number, c: number) => [number, number, number];
export const ocrenginebuilder_detModel: (a: number, b: number, c: number, d: number, e: number) => number;
export const ocrenginebuilder_dictionaryText: (a: number, b: number, c: number) => number;
export const ocrenginebuilder_docOrientationModel: (a: number, b: number, c: number, d: number, e: number) => number;
export const ocrenginebuilder_inferenceThreads: (a: number, b: number) => number;
export const ocrenginebuilder_new: () => number;
export const ocrenginebuilder_recBatchSize: (a: number, b: number) => number;
export const ocrenginebuilder_recModel: (a: number, b: number, c: number, d: number, e: number) => number;
export const ocrenginebuilder_textlineOrientationModel: (a: number, b: number, c: number, d: number, e: number) => number;
export const threadsSupported: () => number;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_mainJS: (a: number) => any;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_exn_store_command_export: (a: number) => void;
export const __externref_table_alloc_command_export: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc_command_export: (a: number, b: number) => number;
export const __wbindgen_realloc_command_export: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc_command_export: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
